### PR TITLE
Update calculater.py

### PR DESCRIPTION
**Pull request by gnsJhenJie**
這是個拉要求

### CODE REVIEW

**Comment by larrychen20011120** [comment]
> 這是個拉要求

I can do whatever I want. 
I'm gay to write down the value of pi as many digits as I can after the decimal point.

**Comment by gnsJhenJie** [comment]
@larrychen20011120
> > 這是個拉要求
> 
> I can do whatever I want.  
>
To disprove "I can do whatever I want", we use one counterexample.
You cannot make "1+1=3."
Hence, you can't do whatever you want.

> I'm gay to write down the value of pi as many digits as I can after the decimal point.  
>
Pi is irrational, so you can't express the precise value by writing down as many digits as you can.

**Comment by larrychen20011120** [comment]
> an't do whatever you want



> @larrychen20011120
> 
> > > 這是個拉要求
> > 
> > 
> > I can do whatever I want.
> 
> To disprove "I can do whatever I want", we use one counterexample.
> You cannot make "1+1=3."
> Hence, you can't do whatever you want.
> 
> > I'm gay to write down the value of pi as many digits as I can after the decimal point.
> 
> Pi is irrational, so you can't express the precise value by writing down as many digits as you can.

You already know that pi is irrational, so there's no tools can express the true value of pi, neither do you.
I know I can't write "1 + 1 = 3", but I am able to append "//" before any statement that are not correct.
Hence, I can do whatever I want if I take some special measures.

**Comment by gnsJhenJie** [comment]
> > an't do whatever you want
> 
> > @larrychen20011120
> > > > 這是個拉要求
> > > 
> > > 
> > > I can do whatever I want.
> > 
> > 
> > To disprove "I can do whatever I want", we use one counterexample.
> > You cannot make "1+1=3."
> > Hence, you can't do whatever you want.
> > > I'm gay to write down the value of pi as many digits as I can after the decimal point.
> > 
> > 
> > Pi is irrational, so you can't express the precise value by writing down as many digits as you can.
> 
> You already know that pi is irrational, so there's no tools can express the true value of pi, neither do you.
> I know I can't write "1 + 1 = 3", but I am able to append "//" before any statement that are not correct.
> Hence, I can do whatever I want if I take some special measures.


When our memory approach infinite, we can write pi to the memory.  
Hence, you are wrong.

**Pull request closed without merging**
